listen = ":8080"
user_api = "http://127.0.0.1:8080"
[dbservers]
    [dbservers.testdb]
        host = "192.168.228.153"
        port = 6605
        user = "customer"
        password = "ccp12345"
        database = "master"